import CoreFlow
import SwiftUI
import Testing

// Real, compiled usage — same reasoning as EndToEndTests/ReflectorTests:
// exercise actual runtime behavior, not just the syntactic shape
// assertMacroExpansion checks (see ShellSyntaxTests for that side).
// @Flowable and @Shell coexist on one type here specifically to verify they
// don't interfere with each other — even though Core itself never carries
// @Flowable (see ShellRendering.swift), relying instead on Swift's own
// memberwise-init synthesis.

@Flowable
@Shell
struct StatefulCard: View {
    @Environment(\.colorScheme) private var colorScheme: ColorScheme
    @Namespace private var ns: Namespace.ID
    @State private var isExpanded: Bool = false
    @SceneStorage("isPinned") private var isPinned: Bool = false
    @FocusState private var isFocused: Bool
    @GestureState private var dragOffset: CGSize = .zero
    @Binding var isOn: Bool
    let title: String
    var subtitle: String?

    // Written once, as ordinary SwiftUI — @Shell copies it verbatim into
    // Core, where the same identifiers resolve against the substituted
    // fields. `heading` below rides along the same way (every non-stored
    // member is copied).
    var body: some View {
        Text(heading)
    }

    var heading: String {
        colorScheme == .dark ? title.uppercased() : title
    }
}

/// A fully-mocked Core, no live view anywhere. The unmapped private
/// wrappers (@Environment/@Namespace/@FocusState/@GestureState) have no
/// parameter at all — self-initializing verbatim copies, out of the
/// memberwise init, they just behave.
@MainActor
private func makeCore(
    isOn: Binding<Bool> = .constant(true),
    title: String = "x",
    subtitle: String? = nil
) -> StatefulCard.Core {
    StatefulCard.Core(
        isExpanded: .constant(false),
        isPinned: .constant(false),
        isOn: isOn,
        title: title,
        subtitle: subtitle
    )
}

/// The hand-written model backing `handWrittenObservableModelBacksEveryBinding`
/// below — the use-site pattern for mocking several bindings at once.
/// File-scoped because @Observable can't attach to a local type.
@Observable @MainActor
private final class CardModel {
    var isExpanded = false
    var isPinned = false
    var isOn = true
}

@MainActor
@Suite struct ShellTests {

    @Test func coreConstructsDirectlyAndReadsBareValues() {
        let snap = makeCore(title: "Settings")
        #expect(snap.isOn == true)  // bare Bool — @Binding unwraps on read
        #expect(snap.isExpanded == false)  // bare Bool, @State's @Binding substitution
        #expect(snap.isPinned == false)  // same substitution for @SceneStorage
        #expect(snap.title == "Settings")
        #expect(snap.subtitle == nil)  // plain `let` on Core, regardless of the original `var`
    }

    @Test func copiedBodyAndHelperEvaluateAgainstTheDefaultEnvironment() {
        // The copied @Environment reads default EnvironmentValues outside a
        // live view (.light — hence un-uppercased). Mocking an environment
        // VALUE is the one thing direct construction can't do (get-only
        // wrapper); hosted, `.environment(\.colorScheme, .dark)` is the
        // native story.
        let snap = makeCore(title: "abc")
        #expect(snap.heading == "abc")
        _ = snap.body
    }

    @Test func bindingFieldWritesThroughRealStorage() {
        // A Binding is just a getter/setter pair, not tied to view identity —
        // writes through Core reach the backing storage.
        var isOnStorage = false
        let snap = makeCore(isOn: Binding(get: { isOnStorage }, set: { isOnStorage = $0 }))
        snap.isOn = true
        #expect(isOnStorage == true)
    }

    @Test func handWrittenObservableModelBacksEveryBinding() {
        // Mocking several bindings at once: Bindable(model).x mints real
        // write-through bindings in plain code, no view needed. Deliberately
        // use-site code, not generated by @Shell.
        let model = CardModel()
        let bindable = Bindable(model)
        let snap = StatefulCard.Core(
            isExpanded: bindable.isExpanded,
            isPinned: bindable.isPinned,
            isOn: bindable.isOn,
            title: "t",
            subtitle: nil
        )
        snap.isExpanded = true
        snap.isOn = false
        #expect(model.isExpanded == true)
        #expect(model.isOn == false)
        #expect(model.isPinned == false)
    }

    @Test func coreFieldsStayMutableForReMocking() {
        // Every Core field is `var` — a copy can be re-mocked field by field.
        var mutable = makeCore()
        mutable.subtitle = "remocked"
        #expect(mutable.subtitle == "remocked")
    }

    @Test func privateVerbatimWrappersAreCompletelySealed() {
        // Private verbatim copies are sealed: no init parameter, no exposed
        // value. All that's observable is that construction works without
        // them and the copied members still evaluate.
        let snap = makeCore(title: "t")
        #expect(snap.title == "t")
        _ = snap.body
    }
}
