import CoreFlow
import SwiftUI
import Testing

// Real, compiled usage — same reasoning as EndToEndTests/ReflectorTests:
// exercise actual runtime behavior, not just the syntactic shape
// assertMacroExpansion checks (see ShellSyntaxTests for that side).
// @Flowable and @Shell coexist on one type here specifically to verify they
// don't interfere with each other — even though Core itself never carries
// @Flowable (see ShellRendering.swift), relying instead on Swift's own
// memberwise-init synthesis.

@Flowable
@Shell
struct StatefulCard: View {
    @Environment(\.colorScheme) private var colorScheme: ColorScheme
    @Namespace private var ns: Namespace.ID
    @State private var isExpanded: Bool = false
    @SceneStorage("isPinned") private var isPinned: Bool = false
    @FocusState private var isFocused: Bool
    @GestureState private var dragOffset: CGSize = .zero
    @Binding var isOn: Bool
    let title: String
    var subtitle: String?

    // Written once, as ordinary SwiftUI — @Shell copies it verbatim into
    // Core, where the same identifiers resolve against the substituted
    // fields. `heading` below rides along the same way (every non-stored
    // member is copied).
    var body: some View {
        Text(heading)
    }

    var heading: String {
        colorScheme == .dark ? title.uppercased() : title
    }
}

/// A directly constructed Core, no live view anywhere. isExpanded (@State)
/// is Core's own @TestState — private, defaulted, out of the memberwise
/// init, logging; isPinned (@SceneStorage, external storage) is a @Binding
/// parameter, mocked like any dependency; the unmapped private wrappers
/// (@Environment/@Namespace/@FocusState/@GestureState) just behave.
@MainActor
private func makeCore(
    isPinned: Binding<Bool> = .constant(false),
    isOn: Binding<Bool> = .constant(true),
    title: String = "x",
    subtitle: String? = nil
) -> StatefulCard.Core {
    StatefulCard.Core(
        isPinned: isPinned,
        isOn: isOn,
        title: title,
        subtitle: subtitle
    )
}

/// The hand-written model backing `handWrittenObservableModelBacksABinding`
/// below — the use-site pattern for backing a genuine @Binding parameter.
/// File-scoped because @Observable can't attach to a local type.
@Observable @MainActor
private final class CardModel {
    var isOn = true
}

@MainActor
@Suite struct ShellTests {

    @Test func coreConstructsDirectlyAndReadsBareValues() {
        let snap = makeCore(title: "Settings")
        #expect(snap.isOn == true)  // bare Bool — @Binding unwraps on read
        #expect(snap.isPinned == false)  // @SceneStorage → @Binding, mocked with .constant
        #expect(snap.title == "Settings")
        #expect(snap.subtitle == nil)
        // isExpanded (@State → @TestState) stays private: Core's own sealed
        // state, out of the memberwise init, observed through the log.
    }

    @Test func externalStorageMocksLikeAnyBinding() {
        // @SceneStorage/@AppStorage are external dependencies — a
        // test-supplied Binding controls the stored value and captures
        // every write the copied body makes.
        var stored = true
        let snap = makeCore(isPinned: Binding(get: { stored }, set: { stored = $0 }))
        #expect(snap.isPinned == true)
        snap.isPinned = false
        #expect(stored == false)
    }

    @Test func bindingFieldWritesThroughRealStorage() {
        // A Binding is just a getter/setter pair, not tied to view identity —
        // writes through Core reach the backing storage.
        var isOnStorage = false
        let snap = makeCore(isOn: Binding(get: { isOnStorage }, set: { isOnStorage = $0 }))
        snap.isOn = true
        #expect(isOnStorage == true)
    }

    @Test func handWrittenObservableModelBacksABinding() {
        // Backing a genuine @Binding parameter: Bindable(model).x mints a
        // real write-through binding in plain code, no view needed.
        // Deliberately use-site code, not generated by @Shell.
        let model = CardModel()
        let snap = StatefulCard.Core(
            isPinned: .constant(false),
            isOn: Bindable(model).isOn,
            title: "t",
            subtitle: nil
        )
        snap.isOn = false
        #expect(model.isOn == false)
    }

    @Test func coreFieldsStayMutableForReMocking() {
        // Core's `var` fields stay mutable — a copy can be re-mocked field
        // by field (a host `let` stays a `let`).
        var mutable = makeCore()
        mutable.subtitle = "remocked"
        #expect(mutable.subtitle == "remocked")
    }

    @Test func privateVerbatimWrappersAreCompletelySealed() {
        // Private verbatim copies are sealed: no init parameter, no exposed
        // value. All that's observable is that construction works without
        // them. (Evaluating body/heading here would read the copied
        // @Environment uninstalled — a SwiftUI runtime issue; hosted is
        // that story.)
        let snap = makeCore(title: "t")
        #expect(snap.title == "t")
    }
}
