import XCTest

/// Mutation-snapshot testing, the action-snapshot pattern: the app appends
/// every CoreModel mutation to a log file (`name = value`, one line each,
/// write order preserved), and the test compares the run's log against the
/// committed snapshot.
///
/// - First run: no saved snapshot — the log is written, the test is skipped
///   with "generating new snapshot". Review the file, commit it.
/// - Every run after: the fresh log must equal the saved one, or the test
///   fails (the data flow changed).
/// - Updating: delete the file in `Snapshots/`, rerun.
///
/// The snapshot file doubles as the log — it's truncated in setUp and
/// regenerated by the run, so a mismatch also shows up as a git diff.
class SnapshotTestCase: XCTestCase {
    private var savedSnapshot: String?

    var snapshotFile: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Snapshots")
            .appendingPathComponent(name)
            .appendingPathExtension("txt")
    }

    override func setUpWithError() throws {
        continueAfterFailure = false
        if FileManager.default.fileExists(atPath: snapshotFile.path) {
            savedSnapshot = try String(contentsOf: snapshotFile, encoding: .utf8)
        }
        try FileManager.default.createDirectory(
            at: snapshotFile.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data().write(to: snapshotFile, options: .atomic)
    }

    override func tearDownWithError() throws {
        guard let savedSnapshot else {
            throw XCTSkip("generating new snapshot: \(snapshotFile.path)")
        }
        let generated = try String(contentsOf: snapshotFile, encoding: .utf8)
        XCTAssertEqual(
            savedSnapshot, generated,
            "Mutation snapshot changed — \(snapshotFile.path) (delete it to re-record)")
    }

    /// Waits until the hidden `logNames` element reads exactly `expected` —
    /// the test's finish line: precisely these names were logged, in this
    /// order, and the run is complete. Values are then verified by the
    /// snapshot diff in tearDown.
    @MainActor
    func expectLogNames(_ app: XCUIApplication, _ expected: String) {
        let names = app.otherElements["logNames"]
        expectation(for: NSPredicate(format: "value == %@", expected), evaluatedWith: names)
        waitForExpectations(timeout: 5)
    }

    /// Launches the app on `scenario` with mutation logging wired to this
    /// test's snapshot file. The app is a separate process; the filesystem
    /// is the shared channel.
    @MainActor
    func launch(scenario: String) -> XCUIApplication {
        let app = XCUIApplication()
        app.launchEnvironment["EXAMPLE_SCENARIO"] = scenario
        app.launchEnvironment["SNAPSHOT_LOG"] = snapshotFile.path
        app.launch()
        return app
    }
}
