import SwiftUI
import Testing
import ValueFlow

// Real, compiled usage — same reasoning as OutFlowTests: exercise actual runtime
// behavior, not just the syntactic shape assertMacroExpansion checks (see
// StatelessNodeSyntaxTests for that side). @DataLayout and @StatelessNode coexist on one
// type here specifically to verify they don't interfere with each other — even
// though StatelessNode itself never carries @DataLayout (see
// StatelessNodeRendering.swift), relying instead on Swift's own memberwise-init
// synthesis.

@DataLayout
@StatelessNode
struct StatefulCard: View {
    @Environment(\.colorScheme) private var colorScheme: ColorScheme
    @Namespace private var ns: Namespace.ID
    @State private var isExpanded: Bool = false
    @FocusState private var isFocused: Bool
    @Binding var isOn: Bool
    let title: String
    var subtitle: String?

    // body itself is generated by @StatelessNode (StatefulCard: View is detected
    // syntactically) — only StatelessNode's own real implementation is hand-written,
    // below.
}

extension StatefulCard.StatelessNode {
    // colorScheme is a plain, internal `let` on StatelessNode — captured once when
    // `.statelessNode` was computed, same as every other field, not live/
    // self-installing. StatelessNode itself is always internal, regardless of
    // StatefulCard's own access — a testing/internal-body seam, not public API.
    var body: some View { Text(colorScheme == .dark ? title.uppercased() : title) }
}

@MainActor
@Suite struct StatelessNodeTests {

    @Test func statelessReadsFieldsDirectlyNoWrappedValueUnwrapNeeded() {
        var isOnStorage = true
        let isOnBinding = Binding<Bool>(get: { isOnStorage }, set: { isOnStorage = $0 })
        let card = StatefulCard(isOn: isOnBinding, title: "Settings")

        let snap = card.statelessNode
        #expect(snap.isOn == true)  // bare Bool, unlike OutFlow's Binding<Bool> — genuine @Binding too
        #expect(snap.isExpanded == false)  // bare Bool, unlike OutFlow's Binding<Bool>
        #expect(snap.isFocused == false)  // bare Bool too, via @FocusState<Bool>.Binding's own unwrap
        #expect(snap.title == "Settings")
    }

    @Test func statelessBindingForARealBindingFieldWritesThrough() {
        // Same reasoning as OutFlow's equivalent test: a genuine caller-supplied
        // @Binding writes through regardless of SwiftUI's view lifecycle.
        var isOnStorage = false
        let isOnBinding = Binding<Bool>(get: { isOnStorage }, set: { isOnStorage = $0 })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        card.statelessNode.isOn = true
        #expect(isOnStorage == true)
    }

    @Test func statelessBindingForAStateFieldDoesNotWriteThroughOutsideALiveView() {
        // Same caveat as OutFlow's: @State's storage only installs once SwiftUI
        // actually renders the view, so a write here silently no-ops.
        let isOnBinding = Binding<Bool>(get: { true }, set: { _ in })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        card.statelessNode.isExpanded = true
        #expect(card.statelessNode.isExpanded == false)
    }

    @Test func statelessFocusStateDoesNotWriteThroughOutsideALiveView() {
        // Same caveat as @State's: @FocusState's storage only installs once
        // SwiftUI actually renders the view, so a write here silently no-ops.
        let isOnBinding = Binding<Bool>(get: { true }, set: { _ in })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        card.statelessNode.isFocused = true
        #expect(card.statelessNode.isFocused == false)
    }

    @Test func statelessFocusStateProjectsARealFocusStateBindingUsableWithFocusedModifier() {
        // snap.$isFocused hands back a genuine FocusState<Bool>.Binding — not a
        // fabricated stand-in — so it plugs directly into `.focused(_:)`, the
        // same as the original @FocusState field would on a live view.
        let isOnBinding = Binding<Bool>(get: { true }, set: { _ in })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        let snap = card.statelessNode
        _ = Text("hi").focused(snap.$isFocused)
    }

    @Test func statelessPlainFieldIsLetRegardlessOfTheOriginalsMutability() {
        // subtitle is a plain `var` on StatefulCard, but StatelessNode is a
        // deterministic snapshot — mutability is never mirrored for a field with
        // no genuine property-wrapper attribute, so it's `let` here, only
        // observable via a fresh `.statelessNode` read.
        let isOnBinding = Binding<Bool>(get: { true }, set: { _ in })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        let snap = card.statelessNode
        #expect(snap.subtitle == nil)
    }

    @Test func statelessCapturesEnvironmentAsAPlainLetField() {
        // @Environment's wrappedValue has no public setter, so its ATTRIBUTE
        // can't be preserved on StatelessNode (verified directly: assigning into
        // an @Environment-attributed property is a compile error) — but a
        // plain, unattributed `let` has no such restriction. Captured once,
        // like @Query/@State, not mirrored live.
        let isOnBinding = Binding<Bool>(get: { true }, set: { _ in })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        let snap = card.statelessNode
        #expect(snap.colorScheme == .light)  // default EnvironmentValues, no live view installed
    }

    @Test func statelessCapturesNamespaceAsAPlainLetFieldLikeEnvironment() {
        // @Namespace has no projectedValue and a get-only wrappedValue (verified
        // directly) — grouped with @Environment, so it's a plain, unattributed
        // `let` here too, captured once per `.statelessNode` read, not mirrored
        // live. Unlike @Environment's default EnvironmentValues, reading
        // @Namespace's wrappedValue outside a live view isn't even stable
        // across separate reads — verified directly: two independent
        // `.statelessNode.ns` reads on the same instance mint two different
        // IDs, since there's no live view identity for it to resolve against.
        // So this only asserts the field is reachable and of the right type,
        // not that it's stable — that instability is @Namespace's own
        // behavior outside SwiftUI's render pipeline, not a bug here.
        let isOnBinding = Binding<Bool>(get: { true }, set: { _ in })
        let card = StatefulCard(isOn: isOnBinding, title: "x")

        let snap = card.statelessNode
        let ns: Namespace.ID = snap.ns
        #expect(ns == ns)
    }
}
