import SwiftSyntax
import SwiftSyntaxMacros

/// Which of SwiftUI's two `body`-shaped protocols the attached type declares
/// conformance to, detected syntactically off its own inheritance clause (see
/// `detectHostKind`) — not a real semantic conformance check (macros never get
/// one; see `detectHostKind`'s own doc comment for exactly what that misses).
enum ShellHostKind {
    case view
    case viewModifier
    case none
}

/// Reads `declaration`'s own inheritance clause — the `: View`/`: ViewModifier`
/// written directly on the type — for a bare `View`/`ViewModifier` identifier,
/// the same textual, syntax-only style `propertyWrapperName` (`StoredProperty.swift`)
/// already uses for property-wrapper attributes.
///
/// **This is textual, not semantic — it cannot be, since macros never get a type
/// checker (verified directly against the pinned swift-syntax dependency itself:
/// `MemberMacro.expansion` receives only `some DeclGroupSyntax` +
/// `some MacroExpansionContext`, no semantic model, on the `603.0.2` this package
/// resolves to within its `600.0.0..<700.0.0` range).** Concretely, this misses:
/// conformance declared in a *separate* extension elsewhere in the file/module,
/// conformance via a typealias or protocol composition, and qualified spellings
/// (`SwiftUI.View`) — only a bare `View`/`ViewModifier` identifier directly in the
/// attached declaration's own inheritance clause is recognized.
func detectHostKind(of declaration: some DeclGroupSyntax) -> ShellHostKind {
    let inherited =
        declaration.inheritanceClause?.inheritedTypes.compactMap {
            $0.type.as(IdentifierTypeSyntax.self)?.name.text
        } ?? []
    if inherited.contains("ViewModifier") { return .viewModifier }
    if inherited.contains("View") { return .view }
    return .none
}

/// Returns the source text of every member that isn't a stored instance
/// property or an initializer — `body`, helper computed properties, methods,
/// `static` members, nested types — dedented, for `renderShell` to copy
/// verbatim into the generated `Core`. Stored instance properties are
/// excluded because they become `Core`'s substituted fields; initializers
/// because copying one would suppress `Core`'s synthesized memberwise init,
/// the only way tests construct a `Core` at all.
///
/// This is what makes the "write it once, test `Core` alone" model work: an
/// attached member macro receives the complete member list *as syntax*, code
/// blocks included, so the copy happens inside `@Shell`'s own expansion —
/// where referencing `Core`'s own fields is legal. (The forbidden thing —
/// verified directly, five different ways — is only referencing names
/// generated by a *different* expansion, which is why no freestanding
/// `#CoreBody`/`#CorePreview` design can do this; see the Previews section of
/// CLAUDE.md.) The copies compile against `Core`'s substituted fields by
/// construction — same names, and every read surface was verified one-to-one
/// (`$x` is `Binding<T>`/`GestureState<T>`/`FocusState<T>.Binding` on both
/// sides, `@Query`'s fetched value reads directly on both) — that equivalence
/// is the entire design of `outFlowFieldType`.
///
/// Syntax-only, like everything here: members declared in a separate
/// extension of the host aren't seen (same limitation as `detectHostKind`)
/// and simply don't appear on `Core`.
func copiedMemberSources(of declaration: some DeclGroupSyntax) -> [String] {
    declaration.memberBlock.members.compactMap { member in
        if member.decl.is(InitializerDeclSyntax.self) { return nil }
        if let varDecl = member.decl.as(VariableDeclSyntax.self) {
            let isStatic = varDecl.modifiers.contains {
                $0.name.tokenKind == .keyword(.static) || $0.name.tokenKind == .keyword(.class)
            }
            // Stored instance properties (observer-only accessors included)
            // are Core's substituted fields, not copies. Static stored
            // properties ARE copied — a body referencing `constant` unqualified
            // needs Core to carry its own.
            let isStored = varDecl.bindings.allSatisfy { binding in
                binding.accessorBlock.map { !isComputed($0) } ?? true
            }
            if !isStatic && isStored { return nil }
        }
        return dedented(member.decl.trimmedDescription)
    }
}

/// Strips the common leading indentation from every line after the first.
/// `trimmedDescription` removes only the *node's* leading trivia — inner
/// lines keep the columns they had in the host's source (member level,
/// typically 4) — and the expansion machinery then shifts every line by the
/// splice position again, double-indenting the copied body inside `Core`.
/// Dedenting to a column-0 baseline first makes the copy land at the same
/// clean nesting a hand-written member would have.
private func dedented(_ source: String) -> String {
    let lines = source.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
    guard lines.count > 1 else { return source }
    let indents = lines.dropFirst()
        .filter { !$0.allSatisfy(\.isWhitespace) }
        .map { $0.prefix(while: { $0 == " " }).count }
    guard let minIndent = indents.min(), minIndent > 0 else { return source }
    return
        ([lines[0]]
        + lines.dropFirst().map { line in
            String(line.dropFirst(min(minIndent, line.prefix(while: { $0 == " " }).count)))
        })
        .joined(separator: "\n")
}

/// Adds a nested `Core` struct to the struct, class, or actor it's attached
/// to: the same field set `@Flowable`'s own `OutFlow`/`outFlow` capture
/// (every non-private participating property, plus every recognized private
/// source-of-truth wrapper) as substituted plain fields, plus a verbatim copy
/// of every non-stored member (`copiedMemberSources` above) — so the host is
/// written as one completely ordinary SwiftUI view, and `Core` is its
/// standalone, directly-constructible twin for tests and previews.
///
/// When the attached type's own inheritance clause spells `View` or
/// `ViewModifier` (`detectHostKind`), `Core` is additionally declared to
/// conform to the same protocol — satisfied by the copied
/// `body`/`body(content:)`.
///
/// A separate macro from `@Flowable` — doesn't replace `OutFlow`/`outFlow`, and
/// works with or without `@Flowable` also attached, since it collects the
/// type's stored properties itself.
///
/// Entry-point boilerplate is `validatedProperties`, shared with `@Flowable`;
/// `renderShell` (in `ShellRendering.swift`) does the actual work, reusing
/// `@Flowable`'s own `outFlowProperties`/`outFlowFieldType`/
/// `outFlowFieldReadExpression` (`FlowableRendering.swift`) rather than
/// re-deriving the same field set.
public enum ShellMacro: MemberMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo _: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard
            let (properties, access) = validatedProperties(
                of: declaration, attachedTo: node, macroName: "Shell", in: context
            )
        else {
            return []
        }
        return renderShell(
            properties: properties, access: access, hostKind: detectHostKind(of: declaration),
            copiedMembers: copiedMemberSources(of: declaration))
    }
}
